### ISSUE TITLE
results summary does not work

### ISSUE THREAD

**Issue by takinbo** [nditech/dev-elections#102]
Results summary gives an exception

```
web_1       | Traceback (most recent call last):
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
web_1       |     response = self.full_dispatch_request()
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
web_1       |     rv = self.handle_user_exception(e)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
web_1       |     return original_handler(e)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
web_1       |     return original_handler(e)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
web_1       |     reraise(exc_type, exc_value, tb)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
web_1       |     raise value
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
web_1       |     rv = self.dispatch_request()
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
web_1       |     return self.view_functions[rule.endpoint](**req.view_args)
web_1       |   File "/app/apollo/frontend/__init__.py", line 10, in wrapper
web_1       |     return f(*args, **kwargs)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
web_1       |     return func(*args, **kwargs)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/flask_principal.py", line 199, in _decorated
web_1       |     rv = f(*args, **kw)
web_1       |   File "/app/apollo/result_analysis/views_results.py", line 459, in results_analysis
web_1       |     return _voting_results(form_id)
web_1       |   File "/app/apollo/result_analysis/views_results.py", line 245, in _voting_results
web_1       |     for sublocation in location_tree[location_type]:
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
web_1       |     return self._execute_and_instances(context)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
web_1       |     result = conn.execute(querycontext.statement, self._params)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
web_1       |     return meth(self, multiparams, params)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
web_1       |     return connection._execute_clauseelement(self, multiparams, params)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
web_1       |     compiled_sql, distilled_params
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
web_1       |     context)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
web_1       |     exc_info
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
web_1       |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
web_1       |     raise value.with_traceback(tb)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
web_1       |     context)
web_1       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
web_1       |     cursor.execute(statement, parameters)
web_1       | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "name" does not exist
web_1       | LINE 3: WHERE 2 = location.location_type_id ORDER BY name
```

**Comment by blynchNDI** [comment]
Confirming that issue no longer seems to be occurring
